### ISSUE TITLE
Any possibility of adding support for new lines?

### ISSUE THREAD

**Issue by FravBox** [TheJaffaMeme/slashbot#3]
Even with just using `\n` in the content?

**Comment by dwilliamsuk** [comment]
Hi, are you able to expand upon what you mean? Thanks!

**Comment by FravBox** [comment]
If I want to make a tag that says:
```
hello!
more text here.
```

I can't, because I cannot make a new line (on desktop).

My solution to this would be that if a type tag content of:
`hello!\nmore text here.`
The tag would be saved with the new line and when called later, would display as
```
hello!
more text here.
```

**Comment by dwilliamsuk** [comment]
Ahh, what command would this be in relation to? The translate command?

**Comment by FravBox** [comment]
LMAO I have the wrong repo, I am so sorry
